local opt = vim.opt

opt.clipboard = "unnamedplus"
opt.termguicolors = true
opt.showmode = true
opt.backup = false
opt.cmdheight = 0
opt.conceallevel = 0
opt.encoding = "utf-8"
opt.fileencoding = "utf-8"
opt.title = true
opt.hlsearch = true
opt.incsearch = true
opt.inccommand = "nosplit"
opt.mouse = "a"
opt.ignorecase = true
opt.smartcase = true
opt.smartindent = false
opt.splitbelow = true
opt.splitright = true
opt.splitkeep = "cursor"
opt.swapfile = false
opt.undofile = true
opt.updatetime = 300
opt.writebackup = false
opt.expandtab = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.cursorline = false
opt.laststatus = 3
opt.number = true
opt.relativenumber = false
opt.signcolumn = "yes"
opt.wrap = false
opt.scrolloff = 8
opt.listchars = {
  tab = "󰌒 ",
  trail = "•",
  nbsp = "␣",
}
opt.list = true
opt.showbreak = "↪ "
