-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'



local mod = "Super_L"

local terminal = "kitty"

hl.config({
    animations = {
        enabled = true,
    },
})

hl.bind(mod .. " + " .. "B", hl.dsp.exec_cmd("zen"))

hl.bind(mod .. " + " .. "E", hl.dsp.exec_cmd("vesktop --gtk-version=4 --ozone-platform=wayland"))

hl.bind(mod .. " + " .. "S", hl.dsp.exec_cmd("steam"))

hl.bind(mod .. " + " .. "I", hl.dsp.exec_cmd("scr"))

hl.bind(mod .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))

hl.bind(mod .. " + " .. "Space", hl.dsp.exec_cmd("rofi -show drun"))

hl.bind(mod .. " + " .. "P", hl.dsp.exec_cmd("cliphist list| rofi -dmenu| cliphist decode| wl-copy"))

hl.bind(mod .. " + " .. "X", hl.dsp.window.close())

hl.bind(mod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "Q", hl.dsp.exit())

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.layout("swapcol l"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.layout("swapcol r"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.layout("movewindowto u"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.layout("movewindowto d"))

-- TODO: manual review (unknown dispatcher: Fullscreen)
-- hl.bind("$mod + SHIFT + F", hl.dsp.Fullscreen())

hl.bind(mod .. " + " .. "C", hl.dsp.layout("togglefit"))

hl.bind(mod .. " + " .. "F", hl.dsp.layout("fit active"))

hl.bind(mod .. " + " .. "ALT" .. " + " .. "F", hl.dsp.layout("promote"))

hl.bind(mod .. " + " .. "Tab", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "Tab", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mod .. " + " .. "period", hl.dsp.exec_cmd("noctalia msg session lock"))

hl.bind(mod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

hl.bind(mod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.config({
    binds = {
        scroll_event_delay = 0,
    },
})

hl.config({
    decoration = {
        blur = {
            brightness = 0.920000,
            contrast = 1,
            enabled = true,
            noise = 0.010000,
            passes = 3,
            popups = true,
            size = 4,
        },
        shadow = {
            enabled = true,
            range = 3,
            render_power = 3,
        },
        rounding = 6,
    },
})

hl.config({
    dwindle = {
        force_split = 2,
        preserve_split = true,
        pseudotile = false,
    },
})

hl.config({
    general = {
        allow_tearing = true,
        border_size = 3,
        gaps_in = 5,
        gaps_out = 9,
        layout = "scrolling",
        col = {
            active_border = "rgb(77adb1)",
            inactive_border = "rgb(191c25)",
        },
    },
})

hl.config({
    input = {
        follow_mouse = 1,
        kb_layout = "us",
        kb_options = "ctrl:nocaps",
        repeat_delay = 270,
        repeat_rate = 50,
    },
})

hl.config({
    master = {
        smart_resizing = true,
    },
})

hl.config({
    misc = {
        allow_session_lock_restore = true,
        disable_autoreload = false,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 1,
        initial_workspace_tracking = 0,
    },
})

hl.monitor({
    output   = "DP-3",
    mode     = "2560x1440@100",
    position = "0x0",
    scale    = 1,
    transform = 1,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "3840x2160@120",
    position = "1440x0",
    scale    = 1,
})

hl.monitor({
    output   = "DP-1",
    mode     = "2560x1440@120",
    position = "5280x0",
    scale    = 1,
    transform = 3,
})


hl.window_rule({
    name  = "match_class___xdg-de",
    match = {
        class = ".*xdg-desktop-portal-gtk",
    },
    float = true;
})

hl.window_rule({
    name  = "match_title__save_fi",
    match = {
        title = "Save File",
    },
    float = true;
})

hl.window_rule({
    name  = "match_title___blob_",
    match = {
        title = ".*blob.*",
    },
    float = true;
})

hl.window_rule({
    name  = "match_title___select",
    match = {
        title = "Select what to share",
    },
    float = true;
})

hl.window_rule({
    match = {
        class = ".*org.pulseaudio.pavucontrol",
    },
    float = true;
})


hl.window_rule({
    match = {
        class = "vesktop",
    },
    workspace = "5",
})

hl.window_rule({
    match = {
        title = ".*ist",
        class = ".*steam.*",
    },
    float = true;
})

hl.window_rule({
    match = {
        title = ".*Steam Settings.*",
    },
    float = true;
})

hl.window_rule({
    match = {
        title = ".*Chat.*",
    },
    float = true;
})


hl.window_rule({
    match = {
        title = ".*Friends List.*",
    },
    float = true;
})

hl.window_rule({
    match = {
        title = ".*started.*",
        class = ".*steam.*",
    },
    float = true;
})

hl.window_rule({
    match = {
        title = ".*Add Non-Steam Game.*",
    },
    float = true;
})

hl.window_rule({
    match = {
        title = ".*Steam- Self Updater.*",
    },
    float = true;
})

hl.window_rule({
    match = {
        title = ".*Manager.*",
        class = ".*steam.*",
    },
})

hl.window_rule({
    match = {
        title = ".*フレンドリスト.*",
    },
    float = true;
})

hl.window_rule({
    match = {
        title = ".*Steam Guard- Computer Authorization Required.*",
    },
    float = true;
})

hl.workspace_rule({
    workspace = 1,
    monitor = "HDMI-A-1",
    is_default = true,
})

hl.workspace_rule({
    workspace = 2,
    monitor = "HDMI-A-1",
    is_default = true,
})

hl.workspace_rule({
    workspace = 3,
    monitor = "HDMI-A-1",
    is_default = true,
})

hl.workspace_rule({
    workspace = 4,
    monitor = "HDMI-A-1",
    is_default = true,
})

hl.workspace_rule({
    workspace = 5,
    monitor = "DP-3",
    is_default = true,
})

hl.workspace_rule({
    workspace = 6,
    monitor = "DP-3",
    is_default = true,
})

hl.workspace_rule({
    workspace = 7,
    monitor = "DP-1",
    is_default = true,
})

hl.workspace_rule({
    workspace = 8,
    monitor = "DP-1",
    is_default = true,
})

hl.workspace_rule({
    workspace = 9,
    monitor = "DP-1",
    is_default = true,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("/nix/store/js1l0300gj2sypwwbm67sma9c7al0p6d-dbus-1.16.2/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
    hl.exec_cmd("systemctl --user enable xdg-desktop-portal-hyprland")
    hl.exec_cmd("hyprctl dispatch exec \"[workspace 2 silent]\" steam")
    hl.exec_cmd("hyprctl dispatch exec \"[workspace 5 silent]\" \"vesktop --gtk-version=4 --ozone-platform=wayland\"")
    hl.exec_cmd("openrgb --startminimized -p ~/.config/OpenRGB/pro.orp")
end)

-- Shutdown
hl.on("hyprland.shutdown", function()
    hl.exec_cmd("systemctl --user stop hyprland-session.target")
end)
