onboarding = false

[terminal]
default_shell = "fish"

[experimental]
kitty_graphics = true

[session]
resume_agents_on_restore = true

[keys]
prefix = "ctrl+space"

[[keys.command]]
key = "prefix+]"
type = "popup"
command = "lazygit"
description = "Open LazyGit"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+t"
type = "popup"
command = "exec fish"
description = "Open shell"
width = "80%"
height = "80%"

[theme]
name = "terminal"
auto_switch = false

[ui]
hide_tab_bar_when_single_tab = true
sidebar_collapsed_mode = "hidden"
sidebar_start_collapsed = true
sidebar_width = 15
sidebar_min_width = 15
show_agent_labels_on_pane_borders = true
